### PR TITLE
Firebase headers

### PR DESCRIPTION
**Pull request by stereobooster**

### CODE REVIEW

**Comment by rl-king** [comment]
Thanks!

**Comment by stereobooster** [comment]
Something is broken at the moment https://elm-hnpwa.firebaseapp.com/js/main-037babc262ca2ddc1f6b.js shows 503

**Comment by rl-king** [comment]
Maybe -> https://status.firebase.google.com/incident/Hosting/18002

**Comment by rl-king** [comment]
The status page is updated and it is

**Comment by stereobooster** [comment]
Ah much nicer

waterfall

We also can make a use of `<link rel=preload>` for JS file. It will cut 200-300ms more

Or serve API from the same domain it will cut DNS part from connection to API

**Comment by rl-king** [comment]
Wow, I did not expect this. That's a whole second faster, awesome, thanks

I looked at using the same domain for the API, seems pretty easy to setup https://github.com/davideast/hnpwa-api/, but you need a paid Firebase account to use functions with external reqs. Will drop the tti quite a bit though.

**Comment by rl-king** [comment]
Ah this isn't the mobile webpage test right?

**Comment by stereobooster** [comment]
> Ah this isn't the mobile webpage test right?

This is 3G medium as far as I can tell, but can happen that I confused settings. I typically use 3G medium Motorola 4G.

**Pull request merged**
